image: Visual Studio 2019

init:
  - echo %PATH%
  # We use a clean PATH to avoid interferences with the hundreds of installed programs.
  - set PATH=c:/Ruby24-x64/bin;c:/Program Files/Git/cmd;c:/Windows/system32;c:/Windows/System32/WindowsPowerShell/v1.0
  # Remove troublesome files from Windows system directory
  - dir c:\windows\system32\l*.dll
  - del c:\windows\system32\libcrypto-1_1-x64.dll c:\windows\system32\libssl-1_1-x64.dll
  # Since system32 is a per-platform-directory, we need to execute the commands through a 32 bit cmd to remove the x86 versions
  - c:\windows\syswow64\cmd.exe /c "dir c:\windows\system32\l*.dll"
  - c:\windows\syswow64\cmd.exe /c "del c:\windows\system32\libcrypto-1_1.dll c:\windows\system32\libssl-1_1.dll"

environment:
    PACMAN_REPOSITORY_NAME: ci.ri2
    BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)
    GPGPASSWD:
        secure: yN0RCzYFBuE4Y2mxfOrkn/IV9pisw4wXb6X4RdG4ZnOyVsi5yC7hFtiUu8i9YFlj
    DEPLOY_TOKEN:
        secure: /XnAP8uTsFB60NFjTnHcPUKSjR6VsGWXhRNlWox7cS4MEBzsgl6cOz/qym2vsZLC

build_script:
    # Update keyring according to https://www.msys2.org/news/#2020-06-29-new-packagers
    - C:\msys64\usr\bin\curl -O http://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
    - C:\msys64\usr\bin\curl -O http://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
    - ridk exec bash -c "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
    - ridk exec bash -c "pacman -U --noconfirm --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
    # Remove gcc-ada and gcc-objc, since they are no longer supported by msys2 and therefore cause a dependency issue
    - C:\msys64\usr\bin\pacman --noconfirm --remove mingw-w64-i686-gcc-ada mingw-w64-i686-gcc-objc mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-objc
    # Update MSYS2
    - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
    # Kill all running msys2 binaries to avoid error "size of shared memory region changed".
    # See https://github.com/msys2/MSYS2-packages/issues/258
    - powershell -Command "Get-Process | Where-Object {$_.path -like 'C:\msys64*'} | Stop-Process"
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

    #- rake upload:lock
    #- ridk exec bash -c "source 'ci-library.sh'; deploy_enabled && cd artifacts && create_pacman_repository 'ci.ri2'"
    ## Upload packages and pacman database to repository release files
    #- rake upload -- artifacts\*
    #- rake upload:unlock
